name: Sample CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Files
        run: ls -la

      - name: Build Project
        run: echo "Build completed successfully!"